myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path(r'login/', views.user_login, name='user_login'),
    path(r'register/', views.register, name='register'),
    path(r'logout/', views.user_logout, name='user_logout'),
    path(r'myorders/', views.myorders, name='myorders'),
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:cat_no>/', views.detail, name='detail'),
    path(r'products/', views.products, name='products'),
    path(r'products/<int:prod_id>/', views.productdetail, name='productdetail'),
    path(r'place_order/', views.place_order, name='place_order'),
 ]

mysiteF22/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='myapp/password_reset_form.html',
        email_template_name='myapp/password_reset_email.html',
        subject_template_name="myapp/password_reset_subject.txt", ), name="password_reset"),

    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='myapp/password_reset_done.html'),
         name="password_reset_done"),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='myapp/password_reset_complete.html'),
         name="password_reset_complete"),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='myapp/password_reset_confirm.html'),
         name="password_reset_confirm"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from PIL import Image

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    # Add validators for stock field in Product model so that it is between 0 and 1000
    stock = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(1000)],
                                 default=100)
    available = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self):
        self.stock += 100
        self.save()


class Client(User):
    PROVINCE_CHOICES = [
        (
            'AB', 'Alberta'
        ),
        (
            'MB', 'Manitoba'
        ),
        (
            'ON', 'Ontario'
        ),
        (
            'QC', 'Quebec'
        ),
    ]

    company = models.CharField(max_length=50, blank=True, null=True)
    shipping_address = models.CharField(max_length=300, null=True,
                                        blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES,
                                default='ON')
    interested_in = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='images/', blank=True)
    def __str__(self):
        return self.first_name


class Order(models.Model):
    valid_value = [
        (
            0, 'Order Cancelled'
        ),
        (
            1, 'Order Placed'
        ),
        (
            2, 'Order Shipped'
        ),
        (
            3, 'Order Delivered'
        ),
    ]
    product = models.ForeignKey(Product, related_name='orders',
                                on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='orders',
                               on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=valid_value, default=1)
    status_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

    def total_cost(self):
        return self.product.price * self.num_units

myapp/forms.py
from django import forms
from myapp.models import Order, Product, Client, Category
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client', 'product', 'num_units']
        widgets = {
            'client': forms.RadioSelect(),
        }
        labels = {
            'num_units': 'Quantity',
            'client': 'Client Name',
        }


class InterestForm(forms.Form):
    interested = forms.ChoiceField(choices=[(1, 'Yes'), (0, 'No')], widget=forms.RadioSelect)
    quantity = forms.IntegerField(min_value=1, initial=1)
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments', required=False)

class SignUpForm(UserCreationForm):
    class Meta:
        model = Client
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'company',
                  'shipping_address', 'city', 'province', 'interested_in', 'image')

myapp/views.py
from datetime import datetime

from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import OrderForm, InterestForm, SignUpForm
from .models import Category, Product, Client, Order
from django.shortcuts import render, get_object_or_404


# Create your views here.
def index(request):
    if request.session.get('last_login'):
        last_login = request.session.get('last_login')
        last_login_flag = True
    else:
        last_login = 'Your last login was more than one hour ago'
        last_login_flag = False

    cat_list = Category.objects.all().order_by('id')[:10]
    prod_list = Product.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'cat_list': cat_list, 'prod_list': prod_list, 'user': request.user, 'last_login': last_login,
                                                'last_login_flag': last_login_flag})


def about(request):
    if request.COOKIES.get('about_visits'):
        visits = int(request.COOKIES.get('about_visits'))
        visits += 1
    else:
        visits = 1
    response = render(request, 'myapp/about.html', {'visits': visits})
    response.set_cookie('about_visits', visits, max_age=300)
    return response


def detail(request, cat_no):
    category = get_object_or_404(Category, pk=cat_no)
    cat_list = Category.objects.all().order_by('id')[:10]
    prod_list = Product.objects.filter(category=cat_no)
    return render(request, 'myapp/detail.html',
                  {'cat_no': cat_no, 'cat_list': cat_list, 'prod_list': prod_list})


def products(request):
    prod_list = Product.objects.all().order_by('id')[:10]
    return render(request, 'myapp/products.html', {'prod_list': prod_list})


@login_required(login_url='/myapp/login')
def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                order.product.stock -= order.num_units
                order.product.save()
                order.save()
                msg = 'Your order has been placed successfully.'
                return render(request, 'myapp/placeorder.html', {'msg': msg})
            else:
                msg = 'We do not have sufficient stock to fill your order.'
            return render(request, 'myapp/placeorder.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist})


@login_required
def productdetail(request, prod_id):
    product = Product.objects.get(pk=prod_id)
    if request.method == "POST":
        form = InterestForm(request.POST)
        if form.is_valid() and int(form.cleaned_data['interested']) == 1:
            product.interested += 1
            product.save()
            msg = 'Order was successful'
            return render(request, 'myapp/order_response.html', {'msg': msg})
        else:
            msg = 'Some error occured in passing the form'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = InterestForm()
    return render(request, 'myapp/productdetail.html', {'form': form, 'product': product})


def user_login(request):
    if request.method == 'POST':
        # form = LoginForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = str(datetime.now())
                request.session.set_expiry(3600)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            return HttpResponse("Invalid login details")
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required(login_url='/myapp/login')
def myorders(request):
    current_user = request.user
    msg = ""
    if not current_user.is_active:
        msg = "You are not a Registered Client"
        return render(request, 'myapp/myorders.html', {'msg': msg})
    else:
        order_list = Order.objects.filter(client__id=current_user.id)
        interested_in = Product.objects.filter(interested__gt=0)
        return render(request, 'myapp/myorders.html', {'msg': msg, 'firstname': current_user.first_name,
                                                       'lastname': current_user.last_name,
                                                       'order_list': order_list, 'interested_in': interested_in})

def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            pwd = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=pwd)
            login(request, user)
            return HttpResponseRedirect(reverse('myapp:index'))
        else:
            return HttpResponse('Invalid')
    form = SignUpForm()
    return render(request, 'myapp/register.html', {'form': form})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<h1>Online Store APP</h1>
    You have visited this page {{ visits }} time.
<p>This is a online store app</p>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
    <h1>Online Store APP</h1>
    <p>This is a online store app</p>
    <p><a href="{% url 'myapp:index' %}">Back to index page</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'myapp/style.css' %}"
    />
    <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
  </head>
  <body>
    <div>
      <h1>{% block myhdg %}Hello {{ user }} {% endblock %}</h1>
      {% block body_block %}*** {% endblock %}
    </div>
    <hr />
    <div>
      <ul>
        <li class="hbar1">
          <a href="/myapp/about/">Find out about this site</a>
        </li>
        <li class="hbar1">
          <a href="{% url 'myapp:index' %}">Click here to return to main page</a
          ><br />
        </li>
        <li class="hbar1">
          <a href="{% url 'myapp:products' %}">Click here to view products</a
          ><br />
        </li>
      </ul>
    </div>
  </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<h1>Category details page</h1>
{% if cat_list %}
        {% for cat in cat_list %}
            {%  if cat.id == cat_no %}
                <h3> Category: </h3>
                <li> {{ cat }}</li>
                <h3> Location of warehouse </h3>
                <li> {{ cat.warehouse }}</li>
            {% endif %}
        {% endfor %}
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
{% if prod_list %}
    <h2>Products of the category</h2>
        {% for prod in prod_list %}
            {%  if prod.category_id == cat_no %}
                <li> {{ prod.name }}</li>
            {% endif %}
        {% endfor %}
{% else %}
    <br>
    <strong>There are no available products!</strong>
{% endif %}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Category details page</title>
</head>
<body>
<h1>Category details page</h1>
{% if cat_list %}
        {% for cat in cat_list %}
            {%  if cat.id == cat_no %}
                <h3> Category: </h3>
                <li> {{ cat }}</li>
                <h3> Location of warehouse </h3>
                <li> {{ cat.warehouse }}</li>
            {% endif %}
        {% endfor %}
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
{% if prod_list %}
    <h2>Products of the category</h2>
        {% for prod in prod_list %}
            {%  if prod.category_id == cat_no %}
                <li> {{ prod.name }}</li>
            {% endif %}
        {% endfor %}
{% else %}
    <br>
    <strong>There are no available products!</strong>
{% endif %}
<p> <a href="{% url 'myapp:index' %}">Move to index page</a></p>
</body>
</html>

myapp/templates/myapp/forget_password.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <div class="row justify-content-center">
        <h1>Request new password</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <form action="{% url 'myapp:forget_password' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input name="email" type="email" id="email" size="80">
                </div>
                <input type="submit" value="Request new password" class="btn btn-primary" />
            </form>
        </div>
        <div class="col-md-3">
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<div class="jumbotron">
    <hr class="my-4">
    <p class="lead">
        {% if user.is_authenticated %}
            <img src="{{ user.image }}" style="width: 150px; height: 150px; border-radius: 50%; margin-right: 25px;">
        <a class="btn btn-primary btn-lg" href="{% url 'myapp:user_logout' %}" role="button">Logout</a>
        <a class="btn btn-primary btn-lg" href="{% url 'myapp:myorders' %}" role="button">myorders</a>
        {% if last_login_flag == True %}
    <p>Last Login @{{ last_login }}</p>
    {% else %}
    {{ last_login }}
    {% endif %}
    {% if cat_list %}
    <h2>List of Categories</h2>
    <ol>
        {% for cat in cat_list %}
        <li>
            <a href="{% url 'myapp:detail' cat.id %}">{{ cat.name }}</a>
        </li>
        {% endfor %}
    </ol>
    {% else %}
    <strong>There are no available categories!</strong>
    {% endif %}
    {% if prod_list %}
    <h2>List of Products</h2>
    <ol>
        {% for prod in prod_list %}
        <li> {{ prod.name}} </li>
        {% endfor %}
    </ol>
    {% else %}
    <strong>There are no available products!</strong>
    {% endif %}
    {% else %}
    <p> You are not logged in please login if u have an accout if not create a new account</p>
    <a class="btn btn-primary btn-lg" href="{% url 'myapp:user_login' %}" role="button">Sign in</a>
    <br>
    <a class="btn btn-primary btn-lg" href="{% url 'myapp:register' %}" role="button">Sign up</a>
    {% endif %}
    </p>
</div>

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %} 

{% block content %} 

<h1> Order Response </h1> 
<p> {{ msg }} </p> 

{% endblock %}

myapp/templates/myapp/password_reset_complete.html
{% extends 'myapp/base.html' %}

{% block body_block %}
  <p>
    Your password has been set now!
    You may go ahead and try <a href="/myapp/login">Signing in</a>
  </p>
{% endblock %}

myapp/templates/myapp/password_reset_form.html
{% extends 'myapp/base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block body_block %}
  <h1>Forgot your password ?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one</p>

  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h1>Place Order</h1>
    {% if prodlist %}
    <ul>
    <li> Product Name - Product price - Product stock </li>
    {% for product in prodlist %}
        <li>{{ product.name }} - {{ product.price }} - {{ product.stock }}</li>
    {% endfor %}
    </ul>
    {% else %}
    <p>No products in cart.</p>
    {% endif %}
    <form action="{% url 'myapp:place_order' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {{ msg }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

myapp/templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}

Product Name: {{ product.name }}
<br/>
Interested People : {{ product.interested }}
<br/>
Price: {{ product.price }}
<form action="/myapp/products/{{ product.id }}/" method="POST">
{% csrf_token %}
    {{  form }}
<input type="submit" value="Submit">
</form>
{% endblock %}

myapp/templates/myapp/products.html
{% extends "myapp/base.html" %}

{% block body_block %}
    <h1>Products</h1>
    <ul>
        {% if prod_list %}
        {% for product in prod_list %}
            <li>
                <a href="{% url 'myapp:products' %}{{product.id}}"> {{ product.name }} </a>
            </li>
        {% endfor %}
        <p><a href="{% url 'myapp:place_order' %}"> Place order for product </a></p>
        {% else %}
            <p> No products available </p>
        {% endif %}

    </ul>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Create an Account{% endblock %}

{% block body_block %}

<div class="container">
    <div class="row">
      <div class="col-md-7 mx-auto">
        <div class="card border-0 shadow rounded-3 my-9">
          <div class="card-body p-9 p-sm-5">
            <h5 class="card-title text-center mb-5 fw-light fs-5">Sign Up</h5>
            <form method="POST" class="form-group">
                {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">Register</button>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock %}